# Generated by Django 2.1.7 on 2019-04-16 10:17

from django.db import migrations, models
import django_ocr_server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md5', models.CharField(blank=True, max_length=32, unique=True, verbose_name='md5')),
                ('file', models.FileField(null=True, upload_to=django_ocr_server.models.set_ocredfile_name, verbose_name='uploaded file')),
                ('file_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='content type')),
                ('text', models.TextField(blank=True, null=True, verbose_name='OCRed content')),
                ('uploaded', models.DateTimeField(auto_now_add=True, verbose_name='uploaded datetime')),
                ('ocred', models.DateTimeField(blank=True, null=True, verbose_name='OCRed datetime')),
                ('ocred_pdf', models.FileField(null=True, upload_to=django_ocr_server.models.set_pdffile_name, verbose_name='Searchable PDF')),
                ('ocred_pdf_md5', models.CharField(blank=True, max_length=32, null=True, verbose_name="Searchable PDF's md5")),
                ('pdf_num_pages', models.IntegerField(blank=True, null=True, verbose_name="PDF's num pages")),
                ('pdf_author', models.CharField(blank=True, max_length=128, null=True, verbose_name="PDF's author")),
                ('pdf_creation_date', models.DateTimeField(blank=True, null=True, verbose_name="PDF's creation date")),
                ('pdf_creator', models.CharField(blank=True, max_length=128, null=True, verbose_name="PDF's creator")),
                ('pdf_mod_date', models.DateTimeField(blank=True, null=True, verbose_name="PDF's mod date")),
                ('pdf_producer', models.CharField(blank=True, max_length=128, null=True, verbose_name="PDF's producer")),
                ('pdf_title', models.CharField(blank=True, max_length=128, null=True, verbose_name="PDF's title")),
            ],
            options={
                'verbose_name': 'OCRedFile',
                'verbose_name_plural': 'OCRedFiles',
            },
        ),
    ]
