# Generated by Django 3.1.4 on 2020-12-30 03:12

from django.db import migrations, models
import django_ocr_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ocr_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocredfile',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to=django_ocr_server.models.set_ocredfile_name, verbose_name='uploaded file'),
        ),
    ]
