# Generated by Django 3.1.4 on 2020-12-30 03:16

from django.db import migrations, models
import django_ocr_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ocr_server', '0002_auto_20201230_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocredfile',
            name='ocred_pdf',
            field=models.FileField(max_length=500, null=True, upload_to=django_ocr_server.models.set_pdffile_name, verbose_name='Searchable PDF'),
        ),
    ]
