language: python
sudo: false
jobs:
  include:
    - name: "Python 3.7 on Linux"
      python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
script: coverage run -m pytest django_ocr_server/tests/
after_success:
  - codecov